"""
Django settings for authors project.

Generated by 'django-admin startproject' using Django 1.11.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import django_heroku
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', ''),

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',

    'corsheaders',
    'django_extensions',
    'rest_framework',
    'rest_framework_swagger',
    'drf_yasg',

    'authors.apps.authentication',
    'authors.apps.core',
    'authors.apps.profiles',
    'authors.apps.articles',
    'authors.apps.comments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'authors.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'authors.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('USER_NAME', ''),
        'PASSWORD': os.environ.get('PASSWORD', ''),
        'HOST': os.environ.get('HOST', ''),
        'PORT': os.environ.get('PORT', ''),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

CORS_ORIGIN_WHITELIST = (
    '0.0.0.0:4000',
    'localhost:4000',
    'localhost:3000',
    'localhost:8080',
    'ah-aquaman-frontend-staging.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-9.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-10.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-11.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-12.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-13.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-14.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-15.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-16.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-17.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-18.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-19.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-20.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-21.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-22.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-23.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-24.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-25.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-26.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-27.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-29.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-30.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-31.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-32.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-33.herokuapp.com',
    'ah-aquaman-frontend-stag-pr-34.herokuapp.com',

)

# Tell Django about the custom `User` model we created. The string
# `authentication.User` tells Django we are referring to the `User` model in
# the `authentication` module. This module is registered above in a setting
# called `INSTALLED_APPS`.
AUTH_USER_MODEL = 'authentication.User'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'authors.apps.core.exceptions.core_exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authors.apps.authentication.backends.JWTAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    )
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        "api_key": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
    },
    'DOC_EXPANSION': 'none',
    'DEFAULT_MODEL_RENDERING': 'example'
}
# Email configurations

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = os.environ.get('EMAIL_PORT', '')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


django_heroku.settings(locals())


# Reading time configurations

# Number of words read per minute
WORD_PER_MINUTE = 265

# Standard number of characters in a word
WORD_LENGTH = 5
