# Generated by Django 2.1.5 on 2019-03-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='readtime',
            new_name='read_time',
        ),
    ]
