# Generated by Django 2.1.5 on 2019-03-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190314_0712'),
        ('articles', '0002_article_readtime'),
    ]

    operations = [
    ]
