# Generated by Django 2.1.5 on 2019-03-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190315_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
    ]
